### ISSUE TITLE
Workspace Folders

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/credo-language-server#59]
## Description

Users sometimes load multiple projects into the same editor instance, which requires the use of workspace folders to make it work well.

## TODO

- [ ] credo-language-server
- [ ] elixir-tools.nvim support
- [ ] elixir-tools.vscode support
- [ ] check with @wkirschbaum that it works in emacs

**Comment by wkirschbaum** [comment]
I started looking into it: https://github.com/elixir-tools/credo-language-server/pull/65, but not sure how quickly it will happen. 

Some ideas:

We probably want to spin up one runtime per workspace: https://github.com/elixir-tools/credo-language-server/blob/main/lib/credo_language_server.ex#L158 and then use a Registry like next-ls's extensions.
